[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.3.2", features = ["postgres", "numeric", "r2d2"] }
anyhow = "1.0.100"
chrono = "0.4.42"
bigdecimal = "0.4.8"